services:
  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8010:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-network
    environment:
      - JENKINS_OPTS=--httpPort=8080
    restart: unless-stopped

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - ci-network
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    restart: unless-stopped

  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: test_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - ci-network
    restart: unless-stopped

networks:
  ci-network:
    driver: bridge

volumes:
  jenkins_home:
  postgres: